### ISSUE TITLE
Could we migrate this repo into KSP-CKAN?

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-status#8]
The status page is an important part of the infrastructure at this point, and KSP-CKAN/CKAN#2789 may open the door to some changes or enhancements, such as data format modifications, easier realtime updates, interactivity, etc. But currently its code lives outside the KSP-CKAN organization, unlike CKAN itself, the bot, the metadata, and the validation scripts.

Could it move to https://github.com/KSP-CKAN/NetKAN-status ? I considered forking it there (as I'm apparently allowed to do as a member of the team), but thought it would be better to ask first.

**Comment by DasSkelett** [comment]
Alternatively to forking, what about the "transfer ownership" option? Never used it, don't know how it works, just came to my mind.

**Comment by techman83** [comment]
This was something I threw together because I wanted to learn a little bit of react and solve a problem we had with error visibility. So consider it done :-)

**Comment by HebaruSan** [comment]
Excellent! :man_astronaut:
